<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robocert" nsURI="http://www.robostar/RoboCert" nsPrefix="robocert">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="robostar"/>
    <details key="modelPluginID" value="robostar.robocert"/>
    <details key="modelDirectory" value="/robostar.robocert/src-gen"/>
    <details key="editDirectory" value="/robostar.robocert.edit/src-gen"/>
    <details key="editorDirectory" value="/robostar.robocert.editor/src-gen"/>
    <details key="testsDirectory" value="/robostar.robocert.tests/src-gen"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="OptionallyNamedElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An element that might be named, but might not be.&#xD;&#xA;&#xD;&#xA;This is usually useful for elements where the name adds some syntactic&#xD;&#xA;complexity but enables cross-reference, and so we want to offer a possible&#xD;&#xA;unnamed variant."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name (can be null)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CertPackage" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//BasicPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A RoboCert package."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//Group" containment="true" eOpposite="#//Group/parent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Any groups in this package.&#xD;&#xA;&#xD;&#xA;Groups form an ordered list because they can lexically depend on things&#xD;&#xA;defined in previous groups."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rcImports" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//RCPackage">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Any RoboChart packages whose contents are to be imported into scope."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" abstract="true" eSuperTypes="#//OptionallyNamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group in a RoboCert package."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//CertPackage" eOpposite="#//CertPackage/groups">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parent package."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecificationGroup" eSuperTypes="#//Group">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group containing specifications."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" containment="true" eOpposite="#//Target/group">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The target of this group."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//ConstAssignment" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constant assignments in effect on this specification group."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageSets" ordered="false"
        upperBound="-1" eType="#//NamedMessageSet" containment="true" eOpposite="#//NamedMessageSet/group">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Any message sets named on the sequence group."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" ordered="false"
        upperBound="-1" eType="#//Actor" containment="true" eOpposite="#//Actor/group">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The actors available in this sequence group."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
        eType="#//Interaction" containment="true" eOpposite="#//Interaction/group">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The interactions inside this sequence group."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A specification target.&#xD;&#xA;&#xD;&#xA;Targets combine several things: a RoboChart element;&#xD;&#xA;a process representing the element from a refinement perspective;&#xD;&#xA;information about the upstream ('context') elements connected to this target;&#xD;&#xA;and information about the downstream elements connected to it.&#xD;&#xA;&#xD;&#xA;To look up the element of a Target, use robostar.robocert.util.resolve.TargetElementResolver."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SpecificationGroup"
        eOpposite="#//SpecificationGroup/target">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The specification group to which this target belongs."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasModuleTarget" abstract="true" eSuperTypes="#//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target whose element is a RCModule."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//RCModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The module referred to by this target."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasControllerTarget" abstract="true"
      eSuperTypes="#//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target whose element is a ControllerDef."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//ControllerDef">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The controller referred to by this target."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentTarget" abstract="true" eSuperTypes="#//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to the behaviour of a component."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleTarget" eSuperTypes="#//ComponentTarget #//HasModuleTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to a RoboChart module.&#xD;&#xA;&#xD;&#xA;Such a target has the robotic platform as its world and its element is the module."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;return &quot;module &quot; + getModule().getName();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerTarget" eSuperTypes="#//ComponentTarget #//HasControllerTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to a RoboChart controller."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;return &quot;controller &quot; + getController().getName();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachineTarget" eSuperTypes="#//ComponentTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to a RoboChart state machine."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;return &quot;state machine &quot; + getStateMachine().getName();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//StateMachineDef">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The state machine referred to by this target."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTarget" eSuperTypes="#//ComponentTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to a RoboChart operation."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;return &quot;operation &quot; + getOperation().getName();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//OperationDef">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operation referred to by this target."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTarget" abstract="true" eSuperTypes="#//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target that contains a collection of elements.&#xD;&#xA;&#xD;&#xA;To resolve the collection given an arbitrary CollectionTarget, use robostar.robocert.util.resolve.TargetComponentsResolver."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InModuleTarget" eSuperTypes="#//CollectionTarget #//HasModuleTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to the contents of a RoboChart module."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;return &quot;components of module &quot; + getModule().getName();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InControllerTarget" eSuperTypes="#//CollectionTarget #//HasControllerTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A target referring to the contents of a RoboChart controller."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;return &quot;components of controller &quot; + getController().getName();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstAssignment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Assigns a value to one or more constants."/>
    </eAnnotations>
    <eOperations name="hasConstant" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Checks whether this assignment maps the given constant."/>
        <details key="body" value="return constants.stream().anyMatch(other -> constant == other);"/>
      </eAnnotations>
      <eParameters name="constant" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Variable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Variable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constant(s) being assigned."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The expression containing the new value of the constant(s)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssertionGroup" eSuperTypes="#//Group">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An assertion group."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//Assertion" containment="true" eOpposite="#//Assertion/group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An assertion."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//AssertionGroup"
        eOpposite="#//AssertionGroup/assertions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The group to which this assertion belongs."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//Property" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The root property of the assertion."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A property in an assertion."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether the assertion must fail to hold for the model to be validated."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreProperty" eSuperTypes="#//Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A core property on the target of a specification group."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SpecificationGroup">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The specification group whose target is being investigated."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//CorePropertyType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The specific type of property being investigated."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CorePropertyType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of core properties."/>
    </eAnnotations>
    <eLiterals name="TIMELOCK_FREE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timelock freedom."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DEADLOCK_FREE" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timed deadlock freedom."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DETERMINISM" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Determinism."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TERMINATION" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Termination."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A value specification."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionValueSpecification" eSuperTypes="#//ValueSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Value specified by an expression."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The expression in question."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardValueSpecification" eSuperTypes="#//ValueSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Value left unconstrained (except by type), and possibly bound."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Variable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An optional variable to receive the value."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Temperature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Temperature modality."/>
    </eAnnotations>
    <eLiterals name="COLD">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Cold temperature; no obligation on model to ensure progress."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HOT" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Hot temperature; obligation on model to ensure progress."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Synchronicity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Whether a communication is synchronous or asynchronous.&#xD;&#xA;&#xD;&#xA;This enumeration may be expanded in future if other forms of semantics become available."/>
    </eAnnotations>
    <eLiterals name="ASYNCHRONOUS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Asynchronous communication."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SYNCHRONOUS" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Synchronous communication."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An interaction spawning a sequence diagram."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SpecificationGroup"
        eOpposite="#//SpecificationGroup/interactions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parent group."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifelines" lowerBound="1"
        upperBound="-1" eType="#//Lifeline" containment="true" eOpposite="#//Lifeline/parent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set of lifelines in this diagram.&#xD;&#xA;&#xD;&#xA;The order determines that in which lifelines are shown in the graphical notation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" lowerBound="1"
        upperBound="-1" eType="#//InteractionFragment" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The fragments of the sequence diagram."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A lifeline specification."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Interaction" eOpposite="#//Interaction/lifelines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The interaction to which this lifeline belongs."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="#//Actor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The actor forming a lifeline."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//VariableList"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variables available for receiving arguments on this lifeline."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A single interaction fragment in a subsequence."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeFragment" abstract="true" eSuperTypes="#//InteractionFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class of fragments imposing time conditions on one lifeline."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="#//Actor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The actor on which this occurrence is occurring."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitFragment" eSuperTypes="#//TimeFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a wait for some amount of time units."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of units to wait, given as a scalar or a set/range expression."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFragment" eSuperTypes="#//InteractionFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A fragment that represents a message communication.&#xD;&#xA;&#xD;&#xA;Unlike UML, there is only one element for both ends of the message."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//Message" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The message itself."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" lowerBound="1"
        eType="#//Temperature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The temperature of this message."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" abstract="true" eSuperTypes="#//InteractionFragment #//OptionallyNamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract class for combined fragments."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockFragment" abstract="true" eSuperTypes="#//CombinedFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Combined fragment that contains exactly one body."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//InteractionOperand"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The body of the block."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptFragment" eSuperTypes="#//BlockFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An optional fragment."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeadlineFragment" eSuperTypes="#//TimeFragment #//BlockFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Fragment imposing a deadline constraint on a block."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The upper bound on the number of time units that can occur in this block."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopFragment" eSuperTypes="#//BlockFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A fragment containing one or more sequence elements in loop."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bound" eType="#//DiscreteBound"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The loop bound, if there is one.  Evaluated once only."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialFragment" abstract="true"
      eSuperTypes="#//InteractionFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Fragment that implies sequentialising of lifelines (ie, strict ordering) within the diagram.&#xD;&#xA;&#xD;&#xA;This class serves mainly to allow matching of all sequential fragments with one type rule."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyFragment" eSuperTypes="#//SequentialFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A sequential fragment that indefinitely performs any message in the attached set.&#xD;&#xA;&#xD;&#xA;Note that this is a sequential fragment, but is not a block fragment (it doesn't have a body) or an occurrence (it can take an arbitrary amount of time).&#xD;&#xA;&#xD;&#xA;This is an extension to UML."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowed" lowerBound="1"
        eType="#//MessageSet" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The messages that may occur during this fragment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UntilFragment" abstract="true" eSuperTypes="#//SequentialFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A sequential fragment where something can be interrupted by occurrences in a 'trigger' operand.&#xD;&#xA;&#xD;&#xA;This fragment implicitly forces strict ordering in the trigger.  This may change in future revisions of the language. &#xD;&#xA;&#xD;&#xA;This is an extension to UML."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//InteractionOperand" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The trigger for exiting the body.&#xD;&#xA;&#xD;&#xA;The intended semantics is that, if any occurrences on the trigger can progress, the body is pre-empted and the trigger runs instead."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyUntilFragment" eSuperTypes="#//UntilFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An AnyFragment with an attached UntilFragment.&#xD;&#xA;&#xD;&#xA;This is an extension to UML."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//AnyFragment"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The any-fragment being wrapped inside this any-until fragment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoUntilFragment" eSuperTypes="#//UntilFragment #//BlockFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A sequential block fragment where the body can be interrupted by occurrences in a 'trigger' operand.&#xD;&#xA;&#xD;&#xA;This fragment implicitly forces strict ordering in both the body and trigger.  This may change in future revisions of the language. &#xD;&#xA;&#xD;&#xA;This is an extension to UML."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutFragment" eSuperTypes="#//BlockFragment #//SequentialFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A sequential block fragment where the body can be pre-empted by a timeout.&#xD;&#xA;&#xD;&#xA;Semantically equivalent to an UntilFragment with a WaitFragment trigger.&#xD;&#xA;&#xD;&#xA;This is an extension to UML."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//WaitFragment" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The wait-fragment being wrapped inside this timeout fragment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteBound">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A possibly open-ended bound on a discrete quantity."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The lower bound, which defaults to the upper bound."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The upper bound, which defaults to infinity."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchFragment" abstract="true" eSuperTypes="#//CombinedFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract fragment containing two or more branches."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="2"
        upperBound="-1" eType="#//InteractionOperand" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The branches available in this fragment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AltFragment" eSuperTypes="#//BranchFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A (provisional) alternative choice fragment."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XAltFragment" eSuperTypes="#//BranchFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A mandatory alternative choice fragment.&#xD;&#xA;&#xD;&#xA;The concept from this comes from STAIRS (Haugen et al., 2003)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParFragment" eSuperTypes="#//BranchFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An interleaving composition fragment."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StrictFragment" eSuperTypes="#//BranchFragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A strict sequencing fragment.&#xD;&#xA;&#xD;&#xA;Each branch induces a synchronisation barrier at its end."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A potentially-guarded subsequence used in a BranchFragment."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="#//Guard"
        containment="true" eOpposite="#//Guard/parent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The guard for this operand."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//InteractionFragment" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The fragments in this operand."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A condition placed on an InteractionOperand."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//InteractionOperand" eOpposite="#//InteractionOperand/guard">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parent branch of this guard."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyGuard" eSuperTypes="#//Guard">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A guard that is always true."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprGuard" eSuperTypes="#//Guard">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A guard that is dependent on the truth value of an expression."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseGuard" eSuperTypes="#//Guard">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A guard that is true if all other guards in the BranchFragment are false.&#xD;&#xA;&#xD;&#xA;It is ill-formed to have multiple ElseGuards in a step, or to have both an&#xD;&#xA;ElseGuard and an EmptyGuard in a step."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A specification of a message."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//MessageTopic"
        containment="true" eOpposite="#//MessageTopic/message">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The topic of the message."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//ValueSpecification" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The argument list for the message."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Endpoint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The source of the message."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Endpoint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The destination of the message."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronicity" lowerBound="1"
        eType="#//Synchronicity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The synchronicity of the message."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outbound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether this message has at least one Endpoint that is a World."/>
        <details key="get" value="return getFrom().isWorld() || getTo().isWorld();"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An endpoint in a message."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="world" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether this endpoint is the World."/>
        <details key="get" value="return this instanceof robostar.robocert.World;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorEndpoint" eSuperTypes="#//Endpoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An endpoint referencing an actor (lifeline)."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;var actor = getActor();&#xD;&#xA;&#x9;&#x9;if (actor == null) return &quot;(null actor)&quot;;&#xD;&#xA;&#x9;&#x9;return actor.toString();&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="#//Actor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The referenced actor."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="World" eSuperTypes="#//Endpoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An endpoint referencing the environment outside of the target."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return &quot;&lt;&lt;world>>&quot;;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageTopic" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A message topic.&#xD;&#xA;&#xD;&#xA;To get the types of all parameters attached to the topic, use robostar.robocert.util.resolve.ParamTypeResolver."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//Message" eOpposite="#//Message/topic">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parent message specification."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTopic" eSuperTypes="#//MessageTopic">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An event message topic (corresponding to a connection)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrom" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Event">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The from-event specification."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eto" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Event">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The to-event specification.&#xD;&#xA;&#xD;&#xA;If missing, we locate the to-event by searching for the opposite of the from-event.  It must have the same name and type."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTopic" eSuperTypes="#//MessageTopic">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An operation message topic."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//OperationSig">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operation signature."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedMessageSet" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A defined and named message set."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//SpecificationGroup"
        eOpposite="#//SpecificationGroup/messageSets">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sequence group on which this message set is defined."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//MessageSet"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The inner message set."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageSet" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A set of message specifications."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefMessageSet" eSuperTypes="#//MessageSet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A message set that is a reference to a previously named message set."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//NamedMessageSet">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The message set being named."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionalMessageSet" eSuperTypes="#//MessageSet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A message set that extensionally enumerates messages."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" ordered="false"
        upperBound="-1" eType="#//Message" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The message specifications held by this message set."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniverseMessageSet" eSuperTypes="#//MessageSet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A message set that includes all messages."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryMessageSet" eSuperTypes="#//MessageSet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A binary set operation over two message sets."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//MessageSet"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The left-hand side."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//MessageSet"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The right-hand side."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BinarySetOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operator."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinarySetOperator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A binary set operator."/>
    </eAnnotations>
    <eLiterals name="UNION">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set union ('or')."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="INTERSECTION" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set intersection ('and')."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DIFFERENCE" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set difference ('except')."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An actor in a sequence.&#xD;&#xA;&#xD;&#xA;Actors have names, for use in lifelines and ExplicitEdges."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SpecificationGroup"
        eOpposite="#//SpecificationGroup/actors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sequence group to which these actors belong."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetActor" eSuperTypes="#//Actor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Actor that stands for the current target."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;if (eIsProxy()) return super.toString();&#xD;&#xA;&#x9;&#x9;var name = getName();&#xD;&#xA;&#x9;&#x9;if (name == null || name.isEmpty()) name = &quot;(untitled)&quot;;&#xD;&#xA;&#x9;&#x9;return &quot;&lt;&lt;target>> &quot; + name;&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentActor" eSuperTypes="#//Actor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Actor that references a component of the target."/>
    </eAnnotations>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;var name = getName();&#xD;&#xA;&#x9;&#x9;if (name == null || name.isEmpty()) name = &quot;(untitled)&quot;;&#xD;&#xA;&#x9;&#x9;return &quot;&lt;&lt;component>> %s: %s&quot;.formatted(name, getNode());&#xD;&#xA;&#x9;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//ConnectionNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Component being referenced.&#xD;&#xA;&#xD;&#xA;It is ill-formed for this node to not be a component of the target,&#xD;&#xA;and also ill-formed for the same component to form multiple actors."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceProperty" eSuperTypes="#//Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A property of a sequence."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" lowerBound="1"
        eType="#//Interaction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Interaction to which this assertion refers."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SequencePropertyType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Type of assertion."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="#//SemanticModel"
        defaultValueLiteral="TIMED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Semantic model under which this assertion should be checked."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SequencePropertyType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Type of sequence assertion."/>
    </eAnnotations>
    <eLiterals name="HOLDS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="All behaviours of the target are included in the sequence."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="IS_OBSERVED" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="All behaviours of the sequence are observable on the target."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemanticModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A semantic model for verification."/>
    </eAnnotations>
    <eLiterals name="TIMED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timed, liveness-aware model.&#xD;&#xA;&#xD;&#xA;Under this model, both permitted and refused behaviour in implementations must conform to specifications.&#xD;&#xA;This extends to timing: deadlines enforced by the target must correspond to deadlines in the specification, for instance."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TRACES" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Traces model.&#xD;&#xA;&#xD;&#xA;This model checks that all traces observable on implementations are allowed by specifications.&#xD;&#xA;It doesn't investigate liveness properties:&#xD;&#xA;as a result, the sequence notion of temperature is irrelevant, as is the distinction between alt and xalt."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSPGroup" eSuperTypes="#//Group">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A CSP fragment in group position."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="csp" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSPProperty" eSuperTypes="#//Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A CSP fragment in property position."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="csp" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
