name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  # Are we performing a full deploy cycle?
  deploy: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'rebuild' || github.event_name == 'workflow_dispatch') }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean install

      - if: env.deploy == 'true'
        name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          # Private key required to access the host
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Hostname or IP to add to the known hosts file
          ssh-host: ${{ secrets.ROBOSTAR_WEB_HOST }}

      - if: env.deploy == 'true'
        name: Making shell scripts executable
        run: chmod +x upload.sh version.sh

      - if: env.deploy == 'true'
        name: Uploading update site
        run: ./upload.sh
        env:
          ROBOSTAR_WEB_ROOT: ${{ secrets.ROBOSTAR_WEB_ROOT }}
          ROBOSTAR_WEB_USER: ${{ secrets.ROBOSTAR_WEB_USER }}
          ROBOSTAR_WEB_HOST: ${{ secrets.ROBOSTAR_WEB_HOST }}

      - if: env.deploy == 'true'
        name: Recompile Textual Editor
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ROBOSTAR_GITHUB_ACTIONS_TOKEN }}
          repository: UoY-RoboStar/robocert-textual
          event-type: rebuild
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'